import os
import sys

def scaffold_component(name):
    """
    Creates folder structure for a new Angular component.
    """
    base_dir = f"src/app/components/{name.lower()}"
    os.makedirs(base_dir, exist_ok=True)
    
    files = [
        f"{name.lower()}.component.ts",
        f"{name.lower()}.component.html",
        f"{name.lower()}.component.css",
        f"{name.lower()}.component.spec.ts"
    ]
    
    print(f"Scaffolding {name} at {base_dir}...")
    for f in files:
        path = os.path.join(base_dir, f)
        with open(path, 'w') as fh:
            fh.write("// Generated by Antigravity Migrator")
        print(f"Created {path}")

if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: python component_scaffolder.py <ComponentName>")
    else:
        scaffold_component(sys.argv[1])
